# render.yaml
# This configuration defines a PostgreSQL database and a web service for deploying the new-api project on Render.

# ----------------- PostgreSQL Database -----------------
# This block defines the persistent database for the application.
databases:
  - name: new-api-db
    # The type for a PostgreSQL database is 'psql'.
    type: psql
    # Specify a stable version of PostgreSQL.
    postgresMajorVersion: 15
    # Use the free plan for PostgreSQL. Note the limitations.
    # See Render's pricing page for more details.
    plan: free

# ----------------- Web Service for New API -----------------
# This block defines the service that builds and runs the application.
services:
  - type: web
    name: new-api
    # Use 'docker' environment for projects with a Dockerfile.
    env: docker
    # Ensure this points to your repository.
    repo: https://github.com/Calcium-Ion/new-api.git
    # Health check to ensure the service is running.
    healthCheckPath: /
    # Environment variables required by the application.
    envVars:
      # Set the timezone.
      - key: TZ
        value: Asia/Shanghai
      # Session secret for user authentication. generateValue creates a secure random string.
      - key: SESSION_SECRET
        generateValue: true
      # Encryption key for database contents. generateValue creates a secure random string.
      - key: CRYPTO_SECRET
        generateValue: true
      # Connect the application to the PostgreSQL database defined above.
      # The connection string is automatically provided by Render.
      - key: SQL_DSN
        fromDatabase:
          name: new-api-db
          property: connectionString
      # Enable memory cache as we are not using Redis in this basic setup.
      - key: MEMORY_CACHE_ENABLED
        value: "true"
