# render.yaml
# This configuration defines a web service and a PostgreSQL database for deploying the new-api project on Render.
services:
  # ----------------- Web Service for New API -----------------
  # This service builds and runs the application using its Dockerfile.
  - type: web
    name: new-api
    # Use 'docker' environment for projects with a Dockerfile
    env: docker
    # Ensure this points to your repository
    repo: https://github.com/Calcium-Ion/new-api.git
    # Health check to ensure the service is running
    healthCheckPath: /
    # Environment variables required by the application
    envVars:
      # Set the timezone
      - key: TZ
        value: Asia/Shanghai
      # Session secret for user authentication. generateValue creates a secure random string.
      - key: SESSION_SECRET
        generateValue: true
      # Encryption key for database contents. generateValue creates a secure random string.
      - key: CRYPTO_SECRET
        generateValue: true
      # Connect the application to the PostgreSQL database defined below.
      # The connection string is automatically provided by Render.
      - key: SQL_DSN
        fromDatabase:
          name: new-api-db
          property: connectionString
      # Enable memory cache as we are not using Redis in this basic setup.
      - key: MEMORY_CACHE_ENABLED
        value: "true"
  # ----------------- PostgreSQL Database -----------------
  # This service provides a persistent database for the application.
  - type: postgres
    name: new-api-db
    # Use the free plan for PostgreSQL. Note the limitations.
    # See Render's pricing page for more details.
    plan: free
    # Specify a stable version of PostgreSQL
    version: "15"
